config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_list/urls.py
from django.urls import path

from todo_list.views import (IndexView,
                             TagListView,
                             TaskCreateView,
                             TagCreateView,
                             TaskUpdateView,
                             TaskDeleteView, TagDeleteView, TagUpdateView, UserCreateView, TaskUpdateCompleteStateView,
                             TagDetailView)


urlpatterns = [
    path("",
         IndexView.as_view(),
         name="index"),
    path("tags/",
         TagListView.as_view(),
         name="tag-list"),
    path("tags/<int:pk>/",
         TagDetailView.as_view(),
         name="tag-detail"),
    path("tags/create/",
         TagCreateView.as_view(),
         name="tag-create"),
    path("tags/<int:pk>/update",
         TagUpdateView.as_view(),
         name="tag-update"),
    path("tags/<int:pk>/delete",
         TagDeleteView.as_view(),
         name="tag-delete"),
    path("task_create/",
         TaskCreateView.as_view(),
         name="task-create"),
    path("<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update"),
    path("<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"),
    path("<int:pk>/update_state/",
         TaskUpdateCompleteStateView.as_view(),
         name="task-update-state"),
    path("user_create/",
         UserCreateView.as_view(),
         name="user-create"),
]

app_name = "todo_list"

todo_list/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255,
                            unique=True)

    def __str__(self) -> str:
        return self.name


class User(AbstractUser):
    first_name = models.CharField(max_length=255,
                                  default="John")
    last_name = models.CharField(max_length=255,
                                 default="Doe")
    email = models.EmailField(
        max_length=255,
        null=True,
        blank=True,
        default="johndoe@example.com"
    )


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name="tasks",
                             on_delete=models.CASCADE)

    class Meta:
        ordering = ["is_completed", "-created_at"]

    def __str__(self) -> str:
        return (f"{self.content} ({self.created_at}). "
                f"Is_completed: {self.is_completed}")

todo_list/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from todo_list.models import Tag, Task, User


class BaseTaskDeadlineValidationForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["deadline"]

    def clean_deadline(self) -> str:
        deadline = self.cleaned_data["deadline"]
        if datetime.now() > deadline:
            raise ValidationError("Deadline is already expired! "
                                  f"You cannot set date earlier than {datetime.now()}")
        return deadline


class TaskCreateOrUpdateForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": forms.DateTimeInput(
                format="%Y-%m-%dT%H:%M",
                attrs={
                    "class": "form-control",
                    "placeholder": "Select a date",
                    "type": "datetime-local"
                }
            ),

        }



class UserCreateForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email"
        )

todo_list/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from todo_list.forms import TaskCreateOrUpdateForm, UserCreateForm
from todo_list.models import Task, Tag, User


class IndexView(generic.ListView):
    model = Task
    paginate_by = 3
    template_name = "todo_list/index.html"
    def get_queryset(self):
        self.queryset = Task.objects.filter(user__id=self.request.user.id)

        return self.queryset


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    paginate_by = 5


class TagDetailView(LoginRequiredMixin, generic.DetailView):
    model = Tag


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskCreateOrUpdateForm
    success_url = reverse_lazy("todo_list:index")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskCreateOrUpdateForm
    success_url = reverse_lazy("todo_list:index")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:index")


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")


class TagDetailView(LoginRequiredMixin, generic.DetailView):
    model = Tag


class UserCreateView(generic.CreateView):
    model = User
    form_class = UserCreateForm
    success_url = reverse_lazy("login")


class TaskUpdateCompleteStateView(LoginRequiredMixin, generic.UpdateView):
    def post(self, request, *args, **kwargs) -> redirect:
        task = get_object_or_404(Task, pk=kwargs["pk"])

        task.is_completed = not task.is_completed
        task.save()

        return redirect("todo_list:index")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login'%}?next={{request.path}}" class="btn-dark p-2">Login</a>
      <a href="{% url 'todo_list:user-create'%}?next={% url 'todo_list:index' %}" class="btn-dark p-2">Register</a>
    </li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url "todo_list:index" %}">Home Page</a></li>
  <li class="list-group-item"><a href="{% url "todo_list:tag-list" %}">Tags</a></li>

</ul>

templates/todo_list/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    <strong>Task List</strong>
    <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  {% if user.is_authenticated %}
      {% if task_list %}
        <div class="card bg-secondary">
          {% for task in task_list %}
              <div class="card bg-light m-5" >

                <form action="{% url 'todo_list:task-update-state' pk=task.id %}" method="post">

                  {% csrf_token %}

                  {% if not task.is_completed %}
                    <input
                          type="submit"
                          class="btn btn-success link-to-page pt-1 pb-2"
                          value="Complete" />
                  {% else %}
                    <input
                          type="submit"
                          class="btn btn-secondary link-to-page"
                          value="Undo" />
                  {% endif %}
                  <div class="btn-dark p-2">{{ task.created_at }}</div>
                </form>
                <ul class="list-group">
                  <li class="list-group-item">
                    <strong>{{ task.content }}</strong>
                    <div class="card link-to-page">
                      {% if task.is_completed %}
                        <div class="btn-success link-to-page p-2">Completed</div>

                      {% else %}
                        <div class="btn-danger link-to-page p-2">Not Completed</div>
                      {% endif %}
                      {% if task.deadline %}
                         <div class="btn-primary">{{ task.deadline }}</div>
                      {% else %}
                        <div class="btn-secondary m-auto pl-3 pr-3">No deadlines</div>
                      {% endif %}
                    </div>
                  </li>


                  <li class="list-group-item">
                    <span class="text-muted">Tags:</span>
                    {% for tag in task.tags.all %}
                      <a href="{% url 'todo_list:tag-detail' pk=tag.id %}">#{{ tag }}</a>
                    {% endfor %}
                  </li>
                  <div
                      class="card-footer border-0 bg-light p-2 d-flex justify-content-around"
                    >
                      <a
                        class="btn btn-link m-0 text-reset"
                        href="{% url 'todo_list:task-update' pk=task.id %}"
                        role="button"
                        data-ripple-color="primary"
                        >Update</a>
                      <a
                        class="btn btn-link m-0 text-reset"
                        href="{% url 'todo_list:task-delete' pk=task.id %}"
                        role="button"
                        data-ripple-color="primary"
                        >Delete</a>
                    </div>
                </ul>
              </div>
          {% endfor %}
        </div>
  {% else %}
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-4">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">

              <div class="mb-md-2 mt-md-4 pb-4">
                <h4>Tasks are not found</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
  {% elif not user.is_authenticated %}
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-4">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">

              <div class="mb-md-2 mt-md-4 pb-4">
                <h4>You have to login to see your task list</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  {% endif %}
{% endblock %}

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-4">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">

              <div class="mb-md-2 mt-md-4 pb-4">
                <h1 class="mb-5">Delete tag?</h1>
                 <form action="" method="post">
                  {% csrf_token %}
                  <input type="submit" value="Yes" class="btn btn-danger">
                  <input type="button" onclick="window.location.href='{% url 'todo_list:tag-list' %}'" value="No, I want to return" class="btn btn-success">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/todo_list/tag_detail.html
{% extends "base.html" %}

{% block content %}
  <h1><strong>{{ tag.name }}</strong></h1>
  <h2>Related Tasks to this tag</h2>
  {% if tag.tasks.all %}
    <div class="card bg-secondary">
      {% for task in tag.tasks.all %}
          <div class="card bg-light m-5" >
            <ul class="list-group">
              <li class="list-group-item">
                <strong>{{ task.content }}</strong>
              </li>
                <div
                    class="card-footer border-0 bg-light p-2 d-flex justify-content-around"
                >
                    <a
                      class="btn btn-link m-0 text-reset"
                      href="{% url 'todo_list:task-update' pk=task.id %}"
                      role="button"
                      data-ripple-color="primary"
                      >Update</a>
                    <a
                      class="btn btn-link m-0 text-reset"
                      href="{% url 'todo_list:task-delete' pk=task.id %}"
                      role="button"
                      data-ripple-color="primary"
                      >Delete</a>
                </div>
            </ul>
          </div>
    {% endfor %}
  </div>
  {% else %}
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-4">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">

              <div class="mb-md-2 mt-md-4 pb-4">
                <h4>Tasks are not found</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-4 h-100" id="blockContent" style="margin-left: -50px">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4 pb-5">
                  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
                  <form action="" method="post" novalidate>
                    {% csrf_token %}

                    <div class="form-outline form-white mb-4">
                      {{ form|crispy }}
                      <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                  </form>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}
{% block content %}
  <h1>
    <strong>Tag List</strong>
    <a href="{% url 'todo_list:tag-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  {% if tag_list %}

    {% for tag in tag_list %}
      <div class="card-body bg-secondary">
        <div class="card bg-light m-2" >
          <ul class="list-group">
            <li class="list-group-item">
              {{ tag.name }}
              <a href="{% url 'todo_list:tag-detail' pk=tag.id %}" class="link-to-page"> Detail</a>
            </li>
            <div class="card-footer border-0 bg-light p-2 d-flex justify-content-around">
              <a
                class="btn btn-link m-0 text-reset"
                href="{% url 'todo_list:tag-update' pk=tag.id %}"
                role="button"
                data-ripple-color="primary"
                >Update</a>
              <a
                class="btn btn-link m-0 text-reset"
                href="{% url 'todo_list:tag-delete' pk=tag.id %}"
                role="button"
                data-ripple-color="primary"
                >Delete</a>
            </div>
          </ul>
        </div>
      </div>
      {% endfor %}

  {% else %}
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-4">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">

              <div class="mb-md-2 mt-md-4 pb-4">
                <h4>Tags are not found</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <div class="container py-4 h-100" id="blockContent" style="margin-left: -50px">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-2 mt-md-2 pb-5 mb-3">
                  <h1 class="mb-5">Delete task?</h1>

                  <form action="" method="post">
                    {% csrf_token %}

                    <input type="submit" value="Yes" class="btn btn-danger">
                    <input type="button" onclick="window.location.href='{% url 'todo_list:index' %}'" value="No, I want to return" class="btn btn-success">
                  </form>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-4 h-100" id="blockContent" style="margin-left: -50px">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4 pb-5">
                  <h1> {{ object|yesno:"Update, Create" }} Task</h1>
                  <form action="" method="post" novalidate>
                    {% csrf_token %}

                    <div class="form-outline form-white mb-4">
                      <label class="form-label" for="typeNameX">Content*</label>
                      <textarea name="{{ form.content.name }}" cols="40" rows="10" class="textarea form-control" id="typeNameX" style="height: 188px;"></textarea>
                    </div>
                    <div class="form-outline form-white mb-4">
                      <label class="form-label" for="typeDeadlineX">Deadline*</label>
                      <input type="date" id=typeDeadlineX class="form-control form-control-lg dateinput" placeholder="Select a date" name="{{ form.deadline.name }}">
                    </div>
                    <div class="form-outline form-white mb-4">
                      <label class="form-label" for="typeIsCompletedX">Is Completed</label>
                      <input type="checkbox" name={{ form.is_completed.name }} id="typeIsCompletedX">
                    </div>
                    <div class="form-outline form-white mb-4">
                        {{ form.tags|as_crispy_field }}
                    </div>
                    <div class="form-outline form-white mb-4">
                    </div>
                    <div class="form-outline form-white mb-4">
                      <input type="hidden" name={{ form.user.name }} value="{{ user.id }}" />
                    </div>

                    <input type="submit" value="Submit" class="btn btn-primary">
                  </form>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

templates/todo_list/user_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-4 h-100" id="blockContent" style="margin-left: -50px">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4 pb-5">
                  <h1> Register</h1>
                  <form action="" method="post" novalidate>
                    {% csrf_token %}

                    <div class="form-outline form-white mb-4">
                      {{ form|crispy }}
                      <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                  </form>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


{% endblock %}